### PR TITLE
Add support for Symfony 3

### PR DESCRIPTION
**Pull request by stof**
This needs to be reviewed carefully, as there is no testsuite yet to ensure it works (see #5)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@stof correct me if i'm wrong, there is no BC in the related components :)

**Comment by stof** [comment]
CssSelector has a BC break, but it is not used directly as far as I can tell, but through the DomCrawler component, which takes care of it already (in 2.8+, but using DomCrawler 2.7 with CssSelector 3 would be weird).
Yaml has one too, but the YamlLoader is documented as taking a yaml string, not a file name, so it is good.

Btw, your comment is misleading. I assumed you wanted to say "there is no BC break". Having no backward compatibility would be a huge issue.

**Comment by mickaelandrieu** [comment]
@stof yes, sorry I wanted to say "there is no BC break". fixed my comment :) Thanks for information

**Comment by romainneutron** [comment]
:+1:

**Comment by fabpot** [comment]
merged, thanks.

**Pull request closed without merging**
